version: '3'
services:
  app:
    image: aronpc/php:8.2-nginx
    working_dir: /app
    ports:
      - '${APP_PORT:-8080}:8080'
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/app

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/data/mysql
    ports:
      - '${DB_PORT:-3306}:3306'

  redis:
    image: redis
    ports:
      - '${REDIS_PORT:-6379}:6379'

  mailpit:
    image: axllent/mailpit
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mysql:

networks:
  default:
    external:
      name: web